"""Shared Pydantic data models for the Pop-Health Intelligence Engine.

All data transfer objects are defined here for cross-feature sharing.
Strict typing enforced for PHI/PII safety.
"""

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field, field_validator


# ── Enums ──────────────────────────────────────────────────────────────────

class RiskTier(str, Enum):
    """Patient risk classification."""
    LOW = "low"
    MODERATE = "moderate"
    HIGH = "high"
    CRITICAL = "critical"


class PlanStatus(str, Enum):
    """Care plan validation status from the critic."""
    APPROVED = "approved"
    VETOED = "vetoed"
    NEEDS_REVISION = "needs_revision"


# ── Input Models ───────────────────────────────────────────────────────────

class PatientInput(BaseModel):
    """Clinical input from the EHR — the provider side."""
    patient_id: str = Field(..., description="De-identified patient identifier")
    age: int = Field(..., ge=0, le=120)
    zip_code: str = Field(..., min_length=5, max_length=10)
    conditions: list[str] = Field(
        default_factory=list,
        description="Active diagnoses (e.g., ['diabetes', 'hypertension'])",
    )
    medications: list[str] = Field(
        default_factory=list,
        description="Current medications (e.g., ['metformin', 'lisinopril'])",
    )
    prior_er_visits: int = Field(default=0, ge=0, description="ER visits in last 12 months")
    is_adherent: bool = Field(
        default=True,
        description="Whether the patient is medication-adherent",
    )

    @field_validator("zip_code")
    @classmethod
    def normalize_zip(cls, v: str) -> str:
        """Store ZIP as first 5 digits."""
        return v.split("-")[0].zfill(5)[:5]


class RawSdoHMetrics(BaseModel):
    """Raw social determinants data fetched from an external API (e.g., Census)."""
    zip_code: str
    air_quality_index: float = Field(..., ge=0, le=500, description="AQI (0-500)")
    grocery_access_score: float = Field(..., ge=0, le=100, description="Access score (0=desert, 100=excellent)")
    housing_instability_score: float = Field(..., ge=0, le=100, description="Instability index (0=stable, 100=unstable)")
    transportation_access_score: float = Field(..., ge=0, le=100, description="Access score (0=no access, 100=excellent)")
    crime_rate_per_100k: float = Field(..., ge=0, description="Violent crimes per 100k population")
    education_attainment_pct: float = Field(..., ge=0, le=100, description="% adults with high school diploma")


# ── Feature 1 Output: SDOH Profile ─────────────────────────────────────────

class SdoHProfile(BaseModel):
    """Normalized social risk factors derived from raw metrics."""
    zip_code: str
    air_quality_risk: float = Field(..., ge=0, le=1, description="Normalized 0-1 risk")
    food_desert_risk: float = Field(..., ge=0, le=1, description="Normalized 0-1 risk")
    housing_risk: float = Field(..., ge=0, le=1, description="Normalized 0-1 risk")
    transportation_risk: float = Field(..., ge=0, le=1, description="Normalized 0-1 risk")
    crime_risk: float = Field(..., ge=0, le=1, description="Normalized 0-1 risk")
    education_risk: float = Field(..., ge=0, le=1, description="Normalized 0-1 risk (1=low education)")
    overall_sdoh_risk: float = Field(..., ge=0, le=1, description="Composite SDOH risk")


# ── Feature 2 Output: Risk Profile ─────────────────────────────────────────

class RiskMultiplier(BaseModel):
    """An interaction-based risk multiplier."""
    condition_a: str
    condition_b: str
    multiplier: float = Field(..., ge=1.0, description="Multiplier (>=1.0, 1.0=no amplification)")
    description: str


class RiskProfile(BaseModel):
    """Complete risk assessment for a patient."""
    patient_id: str
    base_risk_score: float = Field(..., ge=0, description="Sum of individual risks before multipliers")
    applied_multipliers: list[RiskMultiplier] = Field(default_factory=list)
    final_risk_score: float = Field(..., ge=0, description="Score after multiplier interactions")
    risk_tier: RiskTier
    primary_risk_factors: list[str] = Field(default_factory=list)
    sdoh_profile: Optional[SdoHProfile] = None


# ── Feature 3 Output: Care Plan ─────────────────────────────────────────────

class ActionItem(BaseModel):
    """A single actionable intervention in a care plan."""
    action: str = Field(..., description="The intervention description")
    category: str = Field(..., description="e.g., 'medication', 'social', 'lifestyle', 'monitoring'")
    priority: str = Field(..., description="'high', 'medium', or 'low'")
    target_date_days: int = Field(..., ge=1, description="Recommended completion timeline in days")


class CarePlan(BaseModel):
    """A prescriptive care plan generated by the LLM and validated by the critic."""
    patient_id: str
    reasoning: str = Field(..., description="Clinical reasoning behind the plan")
    action_items: list[ActionItem]
    status: PlanStatus
    veto_reason: Optional[str] = Field(None, description="Present if status is VETOED")
    triggered_intervention_count: int = Field(..., ge=0, description="Number of interventions triggered")


# ── Feature 4 Output: Financial Impact ─────────────────────────────────────

class FinancialImpact(BaseModel):
    """ROI quantification for an intervention plan."""
    patient_id: str
    risk_tier: RiskTier
    estimated_annual_er_cost: float = Field(..., ge=0, description="Expected annual ER cost without intervention")
    estimated_cost_avoidance: float = Field(..., ge=0, description="Projected savings from intervention")
    intervention_cost: float = Field(..., ge=0, description="Cost of implementing the intervention")
    net_savings: float = Field(..., description="Cost avoidance minus intervention cost")
    confidence_score: float = Field(..., ge=0, le=1, description="Confidence in the estimate (0-1)")
    roi_ratio: float = Field(..., description="Net savings / intervention cost")